/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import clases.basica;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author odmon
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    basica b;
    public main() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/logos/hotel.png")).getImage());
        this.b = new basica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        btn_export = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_reservar = new javax.swing.JButton();
        btn_libre = new javax.swing.JButton();
        btn_ocupada = new javax.swing.JButton();
        panel_g = new javax.swing.JPanel();
        btn_user = new javax.swing.JButton();
        btn_ap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión Hotelera D´Orlo");
        setPreferredSize(new java.awt.Dimension(1000, 630));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 255));
        jLabel7.setText("Exámen Final - Hotel");

        btn_export.setBackground(new java.awt.Color(255, 102, 102));
        btn_export.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_export.setForeground(new java.awt.Color(255, 255, 255));
        btn_export.setText("Cerrar");
        btn_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_reservar.setBackground(new java.awt.Color(102, 153, 255));
        btn_reservar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_reservar.setForeground(new java.awt.Color(255, 255, 255));
        btn_reservar.setText("¡Resevar Ahora!");
        btn_reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservarActionPerformed(evt);
            }
        });

        btn_libre.setBackground(new java.awt.Color(102, 153, 255));
        btn_libre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_libre.setForeground(new java.awt.Color(255, 255, 255));
        btn_libre.setText("Habitaciones Libres");
        btn_libre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_libreActionPerformed(evt);
            }
        });

        btn_ocupada.setBackground(new java.awt.Color(102, 153, 255));
        btn_ocupada.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_ocupada.setForeground(new java.awt.Color(255, 255, 255));
        btn_ocupada.setText("Habitaciones Ocupadas");
        btn_ocupada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ocupadaActionPerformed(evt);
            }
        });

        panel_g.setBackground(new java.awt.Color(204, 204, 255));
        panel_g.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panel_g.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        panel_g.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout panel_gLayout = new javax.swing.GroupLayout(panel_g);
        panel_g.setLayout(panel_gLayout);
        panel_gLayout.setHorizontalGroup(
            panel_gLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        panel_gLayout.setVerticalGroup(
            panel_gLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        btn_user.setBackground(new java.awt.Color(102, 153, 255));
        btn_user.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_user.setText("New User");
        btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userActionPerformed(evt);
            }
        });

        btn_ap.setBackground(new java.awt.Color(102, 153, 255));
        btn_ap.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_ap.setForeground(new java.awt.Color(255, 255, 255));
        btn_ap.setText("Conexión AP");
        btn_ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btn_libre))
                            .addComponent(btn_ocupada)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_reservar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btn_user))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_ap)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_export)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btn_reservar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_libre)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ocupada)
                        .addGap(18, 18, 18)
                        .addComponent(btn_user)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ap)))
                .addGap(18, 18, 18)
                .addComponent(btn_export)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        panel_g.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportActionPerformed
        
        dispose();
    }//GEN-LAST:event_btn_exportActionPerformed

    private void btn_reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservarActionPerformed
        // TODO add your handling code here:
        reservar pr= new reservar(b);
        pr.setSize(600, 350);
        pr.setLocation(5,5);

        panel_g.removeAll();
        panel_g.add(pr, BorderLayout.CENTER);
        panel_g.revalidate();
        panel_g.repaint();
    }//GEN-LAST:event_btn_reservarActionPerformed

    private void btn_libreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_libreActionPerformed
        // TODO add your handling code here:
        libres pl= new libres(b);
        pl.setSize(600, 350);
        pl.setLocation(5,5);

        panel_g.removeAll();
        panel_g.add(pl, BorderLayout.CENTER);
        panel_g.revalidate();
        panel_g.repaint();
    }//GEN-LAST:event_btn_libreActionPerformed

    private void btn_ocupadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ocupadaActionPerformed
        // TODO add your handling code here:
        ocupadas po= new ocupadas(b);
        po.setSize(600, 350);
        po.setLocation(5,5);

        panel_g.removeAll();
        panel_g.add(po, BorderLayout.CENTER);
        panel_g.revalidate();
        panel_g.repaint();
    }//GEN-LAST:event_btn_ocupadaActionPerformed

    private void btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userActionPerformed
        // TODO add your handling code here:
        user pn= new user(b);
        pn.setSize(600, 350);
        pn.setLocation(5,5);

        panel_g.removeAll();
        panel_g.add(pn, BorderLayout.CENTER);
        panel_g.revalidate();
        panel_g.repaint();
    }//GEN-LAST:event_btn_userActionPerformed

    private void btn_apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apActionPerformed
        // TODO add your handling code here:
        AP pa= new AP(b);
        pa.setSize(600, 350);
        pa.setLocation(5,5);

        panel_g.removeAll();
        panel_g.add(pa, BorderLayout.CENTER);
        panel_g.revalidate();
        panel_g.repaint();
    }//GEN-LAST:event_btn_apActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ap;
    private javax.swing.JButton btn_export;
    private javax.swing.JButton btn_libre;
    private javax.swing.JButton btn_ocupada;
    private javax.swing.JButton btn_reservar;
    private javax.swing.JButton btn_user;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JPanel panel_g;
    // End of variables declaration//GEN-END:variables
}
