/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import clases.LecturaYEscritura;
import clases.basica;
import javax.swing.JOptionPane;

/**
 *
 * @author odmon
 */
public class ocupadas extends javax.swing.JPanel {

    /**
     * Creates new form ocupadas
     */
    basica b;
    public ocupadas(basica b) {
        initComponents();
        this.b = b;
        mostrar_reservas();
    }
    
    public void mostrar_reservas(){      
        
       lbl_oc.setText(b.mostrar_reservas());
          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_oc = new javax.swing.JLabel();
        btn_export = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lbl_oc.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lbl_oc.setForeground(new java.awt.Color(51, 51, 51));
        lbl_oc.setText("Aquí se visualizarán las habitaciones ocupadas :)");

        btn_export.setBackground(new java.awt.Color(153, 153, 255));
        btn_export.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_export.setForeground(new java.awt.Color(255, 255, 255));
        btn_export.setText("Guardar al AP");
        btn_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_oc, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_export)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_oc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                .addComponent(btn_export)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportActionPerformed

        try {
            String contenido = lbl_oc.getText();
            String ruta = "C:\\Users\\odmon\\Desktop\\registro_final.txt";
            LecturaYEscritura le = new LecturaYEscritura(ruta, contenido); //Con los datos del arraylist

            le.escribir();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar los datos, reviselos porfavor");
        }

    
    }//GEN-LAST:event_btn_exportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_export;
    private javax.swing.JLabel lbl_oc;
    // End of variables declaration//GEN-END:variables
}
