/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import clases.basica;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author odmon
 */
public class reservar extends javax.swing.JPanel {

    /**
     * Creates new form reservar
     */
    basica b;
    public reservar(basica b) {
        initComponents();
        this.b = b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVisualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        op_hab = new javax.swing.JComboBox<>();
        btn_actualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbl_piso = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_car = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        op_tipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lbl_habi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ced = new javax.swing.JTextPane();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(800, 374));

        btnVisualizar.setBackground(new java.awt.Color(0, 204, 102));
        btnVisualizar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setText("Reservar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Días:");

        op_hab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        op_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_habActionPerformed(evt);
            }
        });

        btn_actualizar.setBackground(new java.awt.Color(255, 153, 153));
        btn_actualizar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setText("Ver Precio");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Piso asignado:");

        lbl_piso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_piso.setForeground(new java.awt.Color(51, 51, 51));
        lbl_piso.setText("--");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Características:");

        lbl_car.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lbl_car.setForeground(new java.awt.Color(51, 51, 51));
        lbl_car.setText("--");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Precio:");

        lbl_precio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_precio.setForeground(new java.awt.Color(51, 51, 51));
        lbl_precio.setText("--");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Tipo:");

        op_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Matrimonial", "Presidencial", "Vacacional" }));
        op_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_tipoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("# Habitación:");

        lbl_habi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_habi.setForeground(new java.awt.Color(51, 51, 51));
        lbl_habi.setText("--");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Fecha de llegada:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Fecha de salida:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Cédula:");

        jScrollPane2.setViewportView(txt_ced);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("(8 máximo).");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnVisualizar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9))
                                        .addGap(50, 50, 50)))))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_car, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_piso))
                            .addComponent(btn_actualizar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(op_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_precio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_habi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(op_hab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addGap(0, 313, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVisualizar)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(op_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(op_hab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_piso))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbl_habi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_car, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_actualizar)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        
        try{
        int piso = Integer.parseInt(lbl_piso.getText());
        int habitacion = Integer.parseInt(lbl_piso.getText());
        
        SimpleDateFormat df= new SimpleDateFormat("dd/MM/yyyy");
        String fecha1=df.format(jd_fecha1.getDate());
        String fecha2=df.format(jd_fecha2.getDate());
        
        String cedula = txt_ced.getText();
        int tmp = 0;
        
        if(!cedula.equals("")){
            
            tmp = b.validar_cedula(cedula);
            
                if(tmp == 1){
                    JOptionPane.showMessageDialog(null, b.Reservar(cedula, fecha1, fecha2, piso, habitacion));
                }
                else{
                    
                    JOptionPane.showMessageDialog(null, "Usted no se encuentra registrado :c ");
                    
                }
        }else{
            JOptionPane.showMessageDialog(null, "¡Ingrese su cédula! :c ");
        }
        
        
        
    
        }
        catch (Exception e){
            
            JOptionPane.showMessageDialog(null, "¡Ups! Algo ha salido mal :( ");
            
        }
    
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void op_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_habActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        
        String tipo = (String) op_tipo.getSelectedItem();
        String habitaciones = (String) op_hab.getSelectedItem();
        int habs = Integer.parseInt(habitaciones);
    
        
                    
                        if(tipo.equals("individual")){

                            int price = habs * 80;
                            String prezio = "$" + String.valueOf(price);
                            int pis0 = (int)(Math.random()*3+1);
                            String piso = String.valueOf(pis0);

                            int hab1 = (int)(Math.random()*80+1);
                            String habi = String.valueOf(hab1);

                            lbl_habi.setText(habi);

                            lbl_precio.setText(prezio);

                            lbl_car.setText("<html>"+ "-Habitación para 1 persona. <p>"+ "-1 cama, 1 televisor. <p>"+"-Servicio de limpieza."            + "</html> ");

                            lbl_piso.setText(piso);

                        }

                        else if(tipo.equals("matrimonial")){

                            int price = habs * 120;
                            String prezio = "$" + String.valueOf(price);
                            int pis0 = (int)(Math.random()*6+3);
                            String piso = String.valueOf(pis0);

                            int hab1 = (int)(Math.random()*120+81);
                            String habi = String.valueOf(hab1);

                            lbl_habi.setText(habi);

                            lbl_precio.setText(prezio);

                            lbl_car.setText("<html>"+ "-Habitación para parejas. <p>"+ "-1 cama, 1 televisor. <p>"+"-Servicio de limpieza. <p>"+"-Acceso a comida."            + "</html> ");

                            lbl_piso.setText(piso);
                        }

                        else if(tipo.equals("presidencial")){

                            int price = habs * 450;
                            String prezio = "$" + String.valueOf(price);
                            int pis0 = (int)(Math.random()*8+7);
                            String piso = String.valueOf(pis0);

                            int hab1 = (int)(Math.random()*300+280);
                            String habi = String.valueOf(hab1);

                            lbl_habi.setText(habi);

                            lbl_precio.setText(prezio);

                            lbl_car.setText("<html>"+ "-PentHouse. <p>"+ "-2 MEGAcamas, 1 TV. <p>"+"-Servicio de limpieza. <p>"+"-Acceso a comida ilimitada."            + "</html> ");

                            lbl_piso.setText(piso);
                        }

                        else if(tipo.equals("vacacional")){

                            int price = habs * 180;
                            String prezio = "$" + String.valueOf(price);
                            int pis0 = (int)(Math.random()*5+1);
                            String piso = String.valueOf(pis0);

                            int hab1 = (int)(Math.random()*200+1);
                            String habi = String.valueOf(hab1);

                            lbl_habi.setText(habi);

                            lbl_precio.setText(prezio);

                            lbl_car.setText("<html>"+ "-Habitación estancia simple. <p>"+ "-4 camas, 2 TVs. <p>"+"-Servicio de limpieza. <p>"+"-Acceso a comida."            + "</html> ");

                            lbl_piso.setText(piso);
                        }
                        
        
                    
                
               
        
        
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void op_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_tipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_car;
    private javax.swing.JLabel lbl_habi;
    private javax.swing.JLabel lbl_piso;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JComboBox<String> op_hab;
    private javax.swing.JComboBox<String> op_tipo;
    private javax.swing.JTextPane txt_ced;
    // End of variables declaration//GEN-END:variables
}
